# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'CoinCraft' do
  pod 'RIBs', :path => 'RIBsLib'
  pod 'RxCocoa', '~> 5.0.0'
  pod 'RxSwift', '~> 5.0.0'
  pod 'SnapKit'
  pod 'RxAlamofire'
  pod 'Alamofire', '~> 4.8'
  pod 'lottie-ios'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
end

target 'Domain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  project '../Domain/Domain/Domain.xcodeproj'
  pod 'RxCocoa', '~> 5.0.0'
  pod 'RxSwift', '~> 5.0.0'
  pod 'RxAlamofire'
  pod 'SwiftyJSON'
end
