# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoinCraft' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RIBs', :path => 'RIBsLib'
  pod 'RxCocoa', '~> 5.0.0'
  pod 'RxSwift', '~> 5.0.0'
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'lottie-ios'
  pod 'Kingfisher'
  pod 'SwiftyJSON'

  # Pods for CoinCraft

end
